name: YaPay
description: Introducing Ya Pay - the white label payment app for businesses to offer a seamless payment experience to their customers.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  flutter_phoenix:
  animation_wrappers:
  shared_preferences:
  flutter_bloc:
  dotted_border:
  carousel_slider:
  google_mobile_ads:
  solid_bottom_sheet:
  flutter_stripe:


dependency_overrides:
  platform: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
#  flutter_launcher_name: ^0.0.1
#  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
flutter_launcher_name:
  name: "YaPay"

flutter_native_splash:

  color: "#ffffff"
  image: assets/splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/footer/
    - assets/profiles/
    - assets/pay/
    - assets/recharge/
    - assets/provider/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_intl:
  enabled: false
  class_name: S
  main_locale: en
