name: payes
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_phoenix: ^1.0.0
  animation_wrappers: 0.0.4
  shared_preferences: ^2.0.5
  flutter_bloc: ^7.0.0
  dotted_border: ^2.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  google_mobile_ads: ^0.13.2
  solid_bottom_sheet: ^0.1.10


dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
#  flutter_launcher_name: ^0.0.1
#  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
flutter_launcher_name:
  name: "Payes"

flutter_native_splash:

  color: "#ffffff"
  image: assets/splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/footer/
    - assets/profiles/
    - assets/pay/
    - assets/recharge/
    - assets/provider/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_intl:
  enabled: false
  class_name: S
  main_locale: en
